### ISSUE TITLE
Please add prompt and try chatGPT-o1

### ISSUE THREAD

**Issue by GBakalkinOAI** [TranslationalBioinformaticsUnit/LLM_assistant_mini-review#1]
Could you please also upload your prompt, because it actually matters a lot how/what you asked LLM to improve/update your code.

Could you please specify chatGPT version, as in my experience o1-PREVIEW is coding better for scanpy-based scripts I tried.

**Comment by AlbertoMaillo** [comment]
Thank you for your comment! I have updated the README file to include the prompt details, as well as the specific ChatGPT version used.
